### ISSUE TITLE
Sugestões para o esquemático

### ISSUE THREAD

**Issue by rogeriomarcondeli** [cnpem-sei/cs-swls-hw#1]
**O capacitor C3 não possui valor definido?**
**Poderia a descrição "GNDA" ficar como "GND-A ou "GND_A"**

![Captura de tela 2023-05-17 105136](https://github.com/cnpem-sei/cs-swls-hw/assets/62963315/5af74fdb-ea93-42f6-ab58-b8d9e57d6fb3)

**Os resistores R1 e R2  poderiam ficar com o designator como 1M**
**Na fórmula poderia indicar qual o designator pertence "RSET"**

![Captura de tela 2023-05-17 105926](https://github.com/cnpem-sei/cs-swls-hw/assets/62963315/edab6706-d54a-4f36-9118-5b345ceccb26)

**U1 seria um regulador 78L05?**
**Poderia a descrição "+5VD" ficar como "+5VDC" ou "+5VCC"**

![Captura de tela 2023-05-17 105723](https://github.com/cnpem-sei/cs-swls-hw/assets/62963315/3d6cc74b-374c-4fa5-836a-7f019c193337)

**Os resistores R6 e R7  poderiam ficar com o designator como 22K**
**Na fórmula poderia indicar qual o designator pertence "RSET" e "ROUT"**

![Captura de tela 2023-05-17 105816](https://github.com/cnpem-sei/cs-swls-hw/assets/62963315/d22cac23-7426-4250-aad4-8c3d9563d648)

**Adicionar ao U5 capacitor de desacoplamento e alterar as descrições de "+5VD"**

![Captura de tela 2023-05-17 110009](https://github.com/cnpem-sei/cs-swls-hw/assets/62963315/9f3b5d59-dfb5-4d53-b34c-a5d102e8752c)

**Alterar as descrições de "+5VD"**

![Captura de tela 2023-05-17 110318](https://github.com/cnpem-sei/cs-swls-hw/assets/62963315/24cd0524-b301-4d8c-84ee-2f5b03cb9a4d)

**Seria interessante utilizar os pinos 3 e 4 dos conectores LEMO "J2" e "J3" como redundância dos sinais de saídas de corrente**
**Porem temos que pensar se correria o risco de ter loops de corrente ao se fazer isso**

![Captura de tela 2023-05-17 110554](https://github.com/cnpem-sei/cs-swls-hw/assets/62963315/1cec5626-02fb-4771-acc7-8edc85c4f6e3)

**Comment by BrunoGomesOliveira** [comment]
Foram realizadas todas as modificações sugeridas com exceção da da ultima pois foi decidido não utilizar redundância para minimizar loops de corrente e pela característica do cabo de conexão que possui apenas 2 vias.
