### ISSUE TITLE
Sugestões para PCB

### ISSUE THREAD

**Issue by rogeriomarcondeli** [cnpem-sei/cs-swls-hw#2]
**Adicionar capacitor C2 mais próximo de U1**

![InkedCaptura de tela 2023-05-24 0918542](https://github.com/cnpem-sei/cs-swls-hw/assets/62963315/cfc5f1d9-063e-4228-825d-37e977713e45)

**Corrigir trilhas**

![InkedCaptura de tela 2023-05-24 0920252](https://github.com/cnpem-sei/cs-swls-hw/assets/62963315/35957314-1a43-4a46-9a35-938fa5441858)

**Comment by BrunoGomesOliveira** [comment]
Foram realizadas as suas modificações na PCB indicadas nas issues.
